# Generated by Django 6.0.7 on 2026-07-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plataform', models.CharField(choices=[('TWITTER', 'Twitter / X'), ('YOUTUBE', 'Youtube'), ('INSTAGRAM', 'Instagram'), ('NEWS', 'Portal de Noticias'), ('REDDIT', 'Reddit')], max_length=20)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('text_content', models.TextField()),
                ('engagement_score', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='stream_core.contentsource')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity_score', models.FloatField()),
                ('label', models.CharField(choices=[('POS', 'Positivo'), ('NEU', 'Neutro'), ('NEG', 'Negativo')], max_length=3)),
                ('extracted_keywords', models.JSONField(default=list)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='stream_core.rawpost')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawpost',
            index=models.Index(fields=['is_processed', 'published_at'], name='stream_core_is_proc_10ce81_idx'),
        ),
    ]
