# Generated by Django 6.0.7 on 2026-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='feed_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
