# Generated by Django 6.0.7 on 2026-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_core', '0002_contentsource_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsource',
            name='last_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
